### ISSUE TITLE
Centos 7 missing symbol

### ISSUE THREAD

**Issue by cinderblocks** [Daniel15/SecureSign#10]
Installed on Centos 7 with ASP Core v2.2.402 and gpgme and gpgme-devel v1.3.2 Release 5.el7

`/usr/lib64/libgpgme.so.11` exists.

```
]# dotnet published/SecureSign.Tools.dll addkey key.pfx

Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'gpgme_set_pinentry_mode' in shared library 'libgpgme.so.11'.
   at GPGME.Native.Unix.NativeMethods.gpgme_set_pinentry_mode(IntPtr ctx, gpgme_pinentry_mode_t mode)
   at Libgpgme.Context.set_PinentryMode(PinentryMode value)
   at SecureSign.Core.Extensions.ServiceCollectionExtensions.<>c.<AddSecureSignCore>b__0_0(IServiceProvider provider) in /opt/SecureSign/src/SecureSign.Core/Extensions/ServiceCollectionExtensions.cs:line 52
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
   at SecureSign.Tools.Program.Main(String[] args) in /opt/SecureSign/src/SecureSign.Tools/Program.cs:line 24
Aborted
```

**Comment by cinderblocks** [comment]
gpgme shipped with Centos7 is too old. Needs updated.

**Comment by Daniel15** [comment]
Looks like `gpgme_set_pinentry_mode` was added in GPGME 1.4.0 (https://www.gnupg.org/documentation/manuals/gpgme/Pinentry-Mode.html) so you need at least that version.
